version:             '2'
services:
    master:
        image:       archzfs-master
        build:       ./master
        restart:     always
        env_file:
            - master/db.env
            - conf.env
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8080"
    db:
        image:       "postgres:9.4"
        restart:     always
        env_file:
            - master/db.env
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        expose:
            - 5432

    worker1:
        image:       archzfs-worker
        build:       ./worker
        environment:
            - WORKER_NAME=archzfs-worker1
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        links:
            - master

    worker2:
        image:       archzfs-worker
        environment:
            - WORKER_NAME=archzfs-worker2
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        links:
            - master

    worker3:
        image:       archzfs-worker
        environment:
            - WORKER_NAME=archzfs-worker3
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        links:
            - master


    worker4:
        image:       archzfs-worker
        environment:
            - WORKER_NAME=archzfs-worker4
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        links:
            - master

    worker5:
        image:       archzfs-worker
        environment:
            - WORKER_NAME=archzfs-worker5
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        links:
            - master

    deploy:
        image:       archzfs-deploy
        build:       ./deploy
        environment:
            - WORKER_NAME=archzfs-deploy
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        links:
            - master
