version:             '2'
services:
    master:
        image:       archzfs-master
        build:       ./master
        restart:     always
        env_file:
            - master/db.env
            - conf.env
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8080"
    db:
        image:       "postgres:9.4"
        restart:     always
        env_file:
            - master/db.env
        volumes:
            - ./cache/postgres-data:/var/lib/postgresql/data
        expose:
            - 5432

    worker:
        image:       archzfs-worker
        build:       ./worker
        environment:
            - WORKER_NAME=archzfs-worker
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./cache/pacman:/var/cache/pacman/pkg:rw
        links:
            - master

    deploy:
        image:       archzfs-deploy
        build:       ./deploy
        environment:
            - WORKER_NAME=archzfs-deploy
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./cache/pacman:/var/cache/pacman/pkg:rw
        links:
            - master
