version: '2'
services:
    buildbot:
        image: archzfs-master
        env_file:
            - docker/master/db.env
            - conf.env
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8080"
    db:
        env_file:
            - docker/master/db.env
        image: "postgres:9.4"
        expose:
            - 5432

    worker:
        image: archzfs-worker
        privileged: true
        volumes:              
              - /sys/fs/cgroup:/sys/fs/cgroup:ro
        links:
            - buildbot
