version:             '2'
services:
    master:
        image:       archzfs-master
        build:       ./master
        restart:     always
        env_file:
            - master/db.env
            - conf.env
        links:
            - db
        depends_on:
            - db
        privileged:  true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8080:8080"
    db:
        image:       "postgres:9.4"
        restart:     always
        env_file:
            - master/db.env
        volumes:
            - ./cache/postgres-data:/var/lib/postgresql/data
        expose:
            - 5432
    deploy:
        image:       archzfs-deploy
        build:       ./deploy
        environment:
            - WORKER_NAME=archzfs-deploy
        env_file:
            - conf.env
        restart:     always
        privileged:  true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./cache/pacman-deploy:/var/cache/pacman/pkg:rw
        links:
            - master
