version: '2'
services:
    master:
        image: archzfs-master
        restart: always
        env_file:
            - docker/master/db.env
            - conf.env
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8080"
    db:
        image: "postgres:9.4"
        restart: always
        env_file:
            - docker/master/db.env
        expose:
            - 5432

    worker:
        image: archzfs-worker
        restart: always
        privileged: true
        volumes:              
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        links:
            - master
